---
title: "data_4-fixing_orthology_trees_workflow"
author: "Daphne Garcia"
date: "2025-12-3"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
  chunk_output_type: console
---


## Goals
This is an updated section of data_3_workflow.Rmd that corresponds to folder 
`Daphne/Floral_metagenoimcs/data_4-fixing-ortholog-trees`. This notebook contains
part 14 of data_3 workflow, the "Blast Orthologs of pectin lyase". I am picking 
up from 4 months ago when the trees were wonky


## Steps

Previously done in data_3_workflow.Rmd:

1.  FastQC quality analysis
2.  Trimmomatic adapter trimming
3.  bowtie filter with all host plants
4.  MetaSpades assembly
5.  MetaQuast check quality assessment of both
6.  megabat2



NOTE: I copied folders data_3/04_metaspades to the data_4-trees directory to run the following code in data_4-trees



### 14. Blast Orthologs of pectin lyase

Here, I'm going to look for orthologs to acinetobacter's pectin lyase in our 
contig files. First, I needed reference pectin lyase, so the closest match I 
found online was pectin lyase from A. apis and A. boissieri (close on Vivi's 
acinetobacter phylogenetic tree)

#### 14.1 getting reference proteins
I combine the reference proteins together and the outgroup proteins together with cat x y z > all.fasta

NOTE: Originally, the problem was that some of the metagenomic pectin lyases on 
the tree were an outgroup, and these metagenomic  pectin lyases did not BLAST to 
any NCBI pectin lyase online.and we found that some of the references were actually 
polygalacturonase that were wrongly labeled on ncbi. For this reason, I 
BLAST-compared all references, and removed polygalacturonase ones. With the 
pectin lyase references that remained, I aligned them on snapgene to make sure, 
and now all of them align. The following references are:

A_apis_5114_CFY84_RS07245.fasta          A_nectaris_EC034_JK153_00405.fasta     A_pollinis_SCC474_12F30_RS13360.fasta
                                         A_pollinis_FNA11_I2F38_RS11510.fasta   A_pollinis_SCC474_12F30_RS13600.fasta
A_nectaris_BB226_JKI99_01090.fasta       A_pollinis_FNA11_I2F38_RS13050.fasta   A_pollinis_SCC477_12F23_RS12130.fasta
A-nectaris_BB362_JKI98_04120.fasta       A_pollinis_FNA3_I2F29_RS11085.fasta    A_pollinis_SCC477_I2F23_RS12035.fasta
A_nectaris_CIP110549_AYER01000003.fasta  A_pollinis_FNA3_I2F29_RS12920.fasta    A_pollinis_SCC477_I2F23_RS13535.fasta
A_nectaris_EC031_JK152_03155.fasta       A_pollinis_SCC474_12F30_RS12835.fasta


#### 14.2 finidng orthologs with BLAST
```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="pectin_lyase_dec9_3"
for sample in 04_metaspades/*; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/pectin_lyase_references/all_references.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample}/contigs.fasta -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 30 && $4 >= 100 && $11 <= 1e-10' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
done
# takes 2 minutes

#print number of orthologs per sample
for subdir in 14_blast_orthologs/2_ortholog_search/*; do
  echo "$(basename "${subdir}")" >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv | wc -l >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
done
  # took 1 min
```
  outputs are in pectin_lyase or polygalacturonase subdirectories within 
  `data_4-trees/14_blast_orthologs/2_ortholog_search` that contain 
  blast_results.filtered.tsv, which are a list of references and their matching 
  nodes according to the BLAST search. Also outputted is 
  `data_3/14_blast_orthologs/2_ortholog_search/all_{pectin_lyase/polygalacturonase}_matches.txt`, 
  which lists the number of matches found per sample
  
  Info on blastn (the function used for my nucleotide blast search):
  output format is a tsv with 12 columns: 
  qseqid (gene sequence id) 
  sseqid (reference genome sequence id) 
  pident (percentage of identical positions) <<<<<<<--------- filter: over 30%
  length (alignment length (sequence overlap)) <<<<<<<<<----- filter: over 100bp
  mismatch (number of mismatches)
  gapopen (number of gap openings)
  qstart (start of alignment in query)
  qend (end of alignment in query)
  sstart (start of alignment in subject)
  send (end of alignment in subject)
  evalue <<<<<<<<<<<<<<<<<<<------------------------ filter: less than 1e-10
  bitscore (like score for evalue)
  
  
  

#### 14.3 grouping and renaming all orthologs
I will use the `2_ortholog_search` subdirectorie's tblastn_results.tsv to make
one large input for MAFFT containing all orthologs from every sample. I also 
need to rename the orthologs to contain both the sample name and the node name

```{bash}

cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

# loop over all ortholog search subdirectories
for sample in 14_blast_orthologs/2_ortholog_search/* ; do
    name=$(basename "$sample")
    tsv="${sample}/${tree_name}/blast_results.filtered.tsv"
    fasta="04_metaspades/$name/contigs.fasta"

    # get unique node names from column 2 of TSV
    nodes=$(cut -f2 "$tsv" | sort -u)

    # extract nonredundant nodes
    for node in $nodes; do
        awk -v node="$node" -v name="$name" '
            BEGIN {found=0}
            /^>/ {
                if(found) {exit}   # stop once we reach the next contig
                found=($0 ~ node) # activate if this is the header we want
            }
            found {
                if(/^>/) {
                    print ">"name"_"node
                } else {
                    print
                }
            }
        ' "$fasta" >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta
    done
done
  #took <5sec
```
Note: I removed >4_FN176_NODE_2 from pectin_lyase.fasta because it was incredibly long (200k bp) and did not BLAST to acineto with ncbi (this was a problem in data_3, and persists in data_4-trees)

DO THIS!!!!!!!!!!!! ^^^^^^^^^^^^


#### 14.4 aligning with MAFFT

```{bash MAFFT, eval = FALSE}

#BEFORE USING MAFFT:
#I combined orthologs reference and outgroup fastas from `14_blast_orthologs/1_references_and_outgroups` together with our samples from `14_blast_orthologs/3_3_orthologs_from_all_samples` with cat:

cat 14_blast_orthologs/1_references_and_outgroups/pectin_lyase_outgroups/all_outgroups.fasta 14_blast_orthologs/1_references_and_outgroups/pectin_lyase_references/all_references.fasta 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta


export PATH=/programs/mafft/bin:$PATH
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

/programs/mafft/bin/mafft --auto --nuc --thread 30 \
14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta > \
14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln
  # took under 1 min
  
# --auto: chooses best strat for this data, which is FFT-NS-i (standard)
# -nuc: assume input is nucleotides
# --thread: to go faster 


```
PECTIN LYASE and POLYGALACTURONASE STRATEGY:
FFT-NS-i (Standard)
 Iterative refinement method (max. 2 iterations)


#### 14.5 IQ tree
```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-tree

#name this tree
mkdir 14_blast_orthologs/5_IQ_tree/${tree_name}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s 14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln -m MFP \
--prefix 14_blast_orthologs/5_IQ_tree/${tree_name}/${tree_name} -B 1000


# -s: input
# -m MFP: modelfinder plus, fo finding right phylo model (Vivi used SYM+R10)
# --prefix: change output destination/name
# -B: bootstrap
# -nt: thread number
#--redo (OPTIONAL): overwrite current tree

#took 1 min 
```
This outputs a folder named after the variable "tree-name", ex: ref-names-dec-9", that contains 10 files outputted by iqtree. I take .treefile or the tree from .iqtree, and create a visualized tree in `https://itol.embl.de/` tree-visualization website

This pipeline (14.1-14.5) is replicable. Meaning, if I do the same steps (and delete 176_NODE_2 after step 14.3), I should get the same tree every time. There is no randomness. The only difference is that the tree may have branch lengths that are a neglible distance different.


### Make tree with RAST reference

Within data_4-trees/14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase


This folder is made Dec 11, 2025. this aligns with benchling "Metagenomic ortholog pectin lyase tree Vivi's 2021 data" notebook

I am trying to make a phylogenetic tree for metagenomic pectin-lyase orthologs found by a BLAST search, with references from the RAST-annotated pectin lyase that Vivi used for her paper. 

For this, I took all orthologs from Vivi's pectin lyase tree from her paper, and I will align it with MAFFT here. Then, I will create a tree to confirm that I have the same clades, since Vivi's tree didn't have which specific strains/orthologs from which strain are in which clade. 

```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
```

To get all of the orthologs into one .fasta file, I ran:
```{bash}
cd  14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase
cat ./*.fasta >> all_PL_ref_fastas.fasta
```

Then, I went into all_PL_ref_fastas.fasta and manually made sure the strain-ortholog name was the header for every fasta block, so that it appears on iTOL tree

PLUS: I created a new file called `all_PL_ref_PLUS_outgroups.fasta` manually added the pectobacterium, odoriferum, pseudomonas outgroups, and also A. apis referene, to include all the members of the tree in Vivi's paper

For MAFFT I ran:

```{bash}
export PATH=/programs/mafft/bin:$PATH
/programs/mafft/bin/mafft --auto --nuc --thread 10 all_PL_ref_PLUS_outgroups.fasta > aligned_orthologs_MAFFT_pectin_lyase.aln
```


This took 3 seconds, used strategy L-INS-i (Probably most accurate, very slow)

For IQ tree I ran:
```{bash}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s aligned_orthologs_MAFFT_pectin_lyase.aln -m MFP --prefix pectin_lyase_tree -B 1000
```


* -m MFP: modelfinder plus
* -B 1000: boostrap

This took 15 seconds

Afterwards, I submitted the tree into iTOL

### Blast PL Orthologs with RAST reference
I will use the same pipeline as above (14.1-14.5) to create a new tree, but with the RAST references

#### 14.1: RAST reference proteins

the references are in `14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta`


#### 14.2 finidng orthologs with BLAST
```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="pectin_lyase_RAST"
for sample in 04_metaspades/*; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample}/contigs.fasta -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 30 && $4 >= 100 && $11 <= 1e-10' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
done
# takes 2 minutes

#print number of orthologs per sample
for subdir in 14_blast_orthologs/2_ortholog_search/*; do
  echo "$(basename "${subdir}")" >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv | wc -l >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
done
  # took 1 min
```
  outputs are in pectin_lyase or polygalacturonase subdirectories within 
  `data_4-trees/14_blast_orthologs/2_ortholog_search` that contain 
  blast_results.filtered.tsv, which are a list of references and their matching 
  nodes according to the BLAST search. Also outputted is 
  `data_3/14_blast_orthologs/2_ortholog_search/all_{pectin_lyase/polygalacturonase}_matches.txt`
  
  NOTE: I am getting the same samples with BLAST matches using this new RAST 
  references compared to the old NCBI references, however every sample using RAST 
  references has around 2-5 less contigs that match the BLAST query. Maybe I can
   modify this with the filtering step, step 3, if I choose.


#### 14.3 grouping and renaming all orthologs
I will use the `2_ortholog_search` subdirectorie's tblastn_results.tsv to make
one large input for MAFFT containing all orthologs from every sample. I also 
need to rename the orthologs to contain both the sample name and the node name

```{bash}

cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

# loop over all ortholog search subdirectories
for sample in 14_blast_orthologs/2_ortholog_search/* ; do
    name=$(basename "$sample")
    tsv="${sample}/${tree_name}/blast_results.filtered.tsv"
    fasta="04_metaspades/$name/contigs.fasta"

    # get unique node names from column 2 of TSV
    nodes=$(cut -f2 "$tsv" | sort -u)

    # extract nonredundant nodes
    for node in $nodes; do
        awk -v node="$node" -v name="$name" '
            BEGIN {found=0}
            /^>/ {
                if(found) {exit}   # stop once we reach the next contig
                found=($0 ~ node) # activate if this is the header we want
            }
            found {
                if(/^>/) {
                    print ">"name"_"node
                } else {
                    print
                }
            }
        ' "$fasta" >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta
    done
done
  #took <5sec
```
Note: I removed >4_FN176_NODE_2 from pectin_lyase.fasta because it was incredibly long (200k bp) and did not BLAST to acineto with ncbi (this was a problem in data_3, and persists in data_4-trees)

DO THIS!!!!!!!!!!!! ^^^^^^^^^^^^


I got the same exact contigs with RAST references as using the previous NCBI
references. At first I was skeptical, since I had less matches with the RAST 
references, but after removing the nonredundant nodes (third step in in step 
14.3), its possible that we got the same contigs. It's actually great, makes me
more assured that these samples are real acinetobacter

#### 14.4 aligning with MAFFT

```{bash MAFFT, eval = FALSE}

#BEFORE USING MAFFT:
#I combined orthologs reference and outgroup fastas from `14_blast_orthologs/1_references_and_outgroups` together with our samples from `14_blast_orthologs/3_3_orthologs_from_all_samples` with cat:

cat 14_blast_orthologs/1_references_and_outgroups/pectin_lyase_outgroups/all_outgroups.fasta 14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta


export PATH=/programs/mafft/bin:$PATH
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

/programs/mafft/bin/mafft --auto --nuc --thread 30 \
14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta > \
14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln
  # took under 1 min
  
# --auto: chooses best strat for this data, which is FFT-NS-i (standard)
# -nuc: assume input is nucleotides
# --thread: to go faster 


```
PECTIN LYASE and POLYGALACTURONASE STRATEGY:
FFT-NS-i (Standard)
 Iterative refinement method (max. 2 iterations)


#### 14.5 IQ tree
```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-tree

#name this tree
mkdir 14_blast_orthologs/5_IQ_tree/${tree_name}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s 14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln -m MFP \
--prefix 14_blast_orthologs/5_IQ_tree/${tree_name}/${tree_name} -B 1000


# -s: input
# -m MFP: modelfinder plus, fo finding right phylo model (Vivi used SYM+R10)
# --prefix: change output destination/name
# -B: bootstrap
# -nt: thread number
#--redo (OPTIONAL): overwrite current tree

#took 1 min 
```
This outputs a folder named after the variable "tree-name", ex: ref-names-dec-9", 
that contains 10 files outputted by iqtree. I take .treefile or the tree from 
.iqtree, and create a visualized tree in `https://itol.embl.de/` tree-visualization 
website

This pipeline (14.1-14.5) is replicable. Meaning, if I do the same steps (and 
delete 176_NODE_2 after step 14.3), I should get the same tree every time. There 
is no randomness. The only difference is that the tree may have branch lengths 
that are a neglible distance different.


Afterwards, I submitted the tree into iTOL




##################################################################################################


### Add new genomes to ortholog tree
I will use the same pipeline as above (14.1-14.5) to BLAST find pectin lyase 
orthologs within 4 new genomes that the lab found in NY: A39, A04, AD04 21SM068,
and MB2 (step 14.2). Then, I will get a fasta file for each genome with the 
contigs that contain pectin lyase (14.3) , and I will align these together with the 
metagenomic pectin lyase contigs and generate a tree with the references, 
outgroups, metagenomic contigs, and new-genome contigs.



#### 14.2 finidng orthologs with BLAST
```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="new_genome_RAST"
for sample in New_NY_Acineto_genomes/*; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample} -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 30 && $4 >= 100 && $11 <= 1e-10' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
done
# takes 2 minutes

#print number of orthologs per sample
for subdir in 14_blast_orthologs/2_ortholog_search/Acineto*; do
  echo "$(basename "${subdir}")" >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv | wc -l >> 14_blast_orthologs/2_ortholog_search/all_${tree_name}_matches.txt
done
  # took 1 min
```
  outputs are in within 
  `data_4-trees/14_blast_orthologs/2_ortholog_search/Acineto_` that contain 
  blast_results.filtered.tsv, which are a list of references and their matching 
  nodes according to the BLAST search. Also outputted is 
  `data_3/14_blast_orthologs/2_ortholog_search/all_{pectin_lyase/polygalacturonase}_matches.txt`


I got 14 matches from A039, D04_21SM068, and A044, and 28 matches from MB2


#### 14.3 grouping and renaming all orthologs
I will use the `2_ortholog_search` subdirectorie's tblastn_results.tsv to make
one large input for MAFFT containing all orthologs from every sample. I also 
need to rename the orthologs to contain both the sample name and the node name

```{bash}
# loop over all ortholog search subdirectories
for sample in 14_blast_orthologs/2_ortholog_search/Acineto_* ; do
    name=$(basename "$sample")
    tsv="${sample}/${tree_name}/blast_results.filtered.tsv"
    fasta="New_NY_Acineto_genomes/$name"

    # get unique node names from column 2 of TSV
    nodes=$(cut -f2 "$tsv" | sort -u)

    # extract nonredundant nodes
    for node in $nodes; do
        awk -v node="$node" -v name="$name" '
            BEGIN {found=0}
            /^>/ {
                if(found) {exit}   # stop once we reach the next contig
                found=($0 ~ node) # activate if this is the header we want
            }
            found {
                if(/^>/) {
                    print ">"name"_"node
                } else {
                    print
                }
            }
        ' "$fasta" >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta
    done
done
  #took <5sec
  


```
Note: A039 node 3 and 21SM068 node 22 were extremely long (300k bp long) so trimmed it.
Procedure for how I trimmed it: I BLASTed it with all acineto pectin lyase 
references from 14.1, and found roughly the location that it aligned to pectin
lyase. From there, I went to geneious and aligned one reference to a 1000bp 
section of where the pectin lyase should be in A039, and from the alignment, 
I was able to accurately obtain the fragment of A039 node 3 that was pectin lyase

I also did this for metagenomic 176_node_2, but node 2 wasn't a great match to 
the references even when cropped, so I think it's best to keep it deleted

#### 14.4 aligning with MAFFT

Now, I will align the references, outgroups, metagenomic, AND new genomes together
into one big tree, so the cat step will include new-genomes too (line 546)

```{bash MAFFT, eval = FALSE}

#BEFORE USING MAFFT:
#I combined orthologs reference and outgroup fastas from `14_blast_orthologs/1_references_and_outgroups` together with our samples from `14_blast_orthologs/3_3_orthologs_from_all_samples` with cat:

cat 14_blast_orthologs/3_orthologs_from_all_samples/pectin_lyase_RAST_PLUS_references_and_outgroups.fasta 14_blast_orthologs/3_orthologs_from_all_samples/new_genome_RAST.fasta >> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta


export PATH=/programs/mafft/bin:$PATH
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

/programs/mafft/bin/mafft --auto --nuc --thread 30 \
14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta > \
14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln
  # took under 1 min
  
# --auto: chooses best strat for this data, which is FFT-NS-i (standard)
# -nuc: assume input is nucleotides
# --thread: to go faster 


```
PECTIN LYASE and POLYGALACTURONASE STRATEGY:
FFT-NS-i (Standard)
 Iterative refinement method (max. 2 iterations)


#### 14.5 IQ tree
```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-tree

#name this tree
mkdir 14_blast_orthologs/5_IQ_tree/${tree_name}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s 14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln -m MFP \
--prefix 14_blast_orthologs/5_IQ_tree/${tree_name}/${tree_name} -B 1000


# -s: input
# -m MFP: modelfinder plus, fo finding right phylo model (Vivi used SYM+R10)
# --prefix: change output destination/name
# -B: bootstrap
# -nt: thread number
#--redo (OPTIONAL): overwrite current tree

#took 1 min 
```
This outputs a folder named after the variable "tree-name", ex: ref-names-dec-9", that contains 10 files outputted by iqtree. I take .treefile or the tree from .iqtree, and create a visualized tree in `https://itol.embl.de/` tree-visualization website

This pipeline (14.1-14.5) is replicable. Meaning, if I do the same steps (and delete 176_NODE_2 after step 14.3), I should get the same tree every time. There is no randomness. The only difference is that the tree may have branch lengths that are a neglible distance different.



### PECTIN LYASE crop and filtered pipeline 1/14

####14.2 for metagenome

```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="PL_cropped_RAST_Jan21_metagenome"
for sample in 04_metaspades/*; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample}/contigs.fasta -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 60 && $4 >= 250 && $11 <= 1e-50' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
     echo "[INFO] Step 4: deduplicating hits (keep highest bit score)..."
     tsv="$OUTDIR/blast_results.filtered.tsv"
     awk '
      {
          if (!best[$2] || $12 > best[$2]) {
              best[$2] = $12
              line[$2] = $0
          }
      }
      END {
          for (c in line)
              print line[c]
      }' "$tsv" > "$tsv.unique"
    
done
# takes 2 minutes

#SANITY CHECK: print tsv of all filtered orthologs
Sanity_output="14_blast_orthologs/2_ortholog_search/all_${tree_name}.tsv"
for subdir in 14_blast_orthologs/2_ortholog_search/*FN*; do
  if [ -s ${subdir}/${tree_name}/blast_results.filtered.tsv.unique ]; then
  echo "$(basename "${subdir}")" >> $Sanity_output
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv.unique >> $Sanity_output
  fi
done
  # took 1 min
  
```  

####14.3 for metagenome
```{bash}
  
tree_name="PL_cropped_RAST_Jan21_metagenome"
OUT_FASTA="14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta"

echo "" > $OUT_FASTA
for sample in 04_metaspades/*; do   
BLAST_TSV="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}/blast_results.filtered.tsv.unique"
CONTIGS_FASTA="${sample}/contigs.fasta"

# Read each line of BLAST TSV
while IFS=$'\t' read -r qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
do
    #save the sample name in a variable:
    sample_name=$(basename "$sample")
    # Determine start and end in increasing order
    if [ "$sstart" -le "$send" ]; then
        START="$sstart"
        END="$send"
        STRAND="+"
    else
        START="$send"
        END="$sstart"
        STRAND="-"
    fi

    # Extract sequence using awk
    SEQ=$(awk -v seqid="$sseqid" -v start="$START" -v end="$END" '
        BEGIN {capture=0; seq=""}
        /^>/ {capture=($0 ~ ">"seqid); next}
        capture {seq=seq $0}
        END {print substr(seq, start, end-start+1)}
    ' "$CONTIGS_FASTA")

    # Reverse complement if needed
    if [ "$STRAND" = "-" ]; then
        SEQ=$(echo "$SEQ" | rev | tr 'ACGTacgt' 'TGCAtgca')
    fi

    # Print to output FASTA with sample name
    echo ">${sample_name}_${sseqid}:${START}-${END}(${STRAND})" >> "$OUT_FASTA"
    # Wrap sequence at 80 chars per line
    echo "$SEQ" | fold -w 80 >> "$OUT_FASTA"

done < "$BLAST_TSV"
done

```

#### 14.2 for A039 MB2 A044 D04

```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="PL_cropped_RAST_Jan21_newgenome"
for sample in New_NY_Acineto_genomes/**; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample} -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 60 && $4 >= 250 && $11 <= 1e-50' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
     echo "[INFO] Step 4: deduplicating hits (keep highest bit score)..."
     tsv="$OUTDIR/blast_results.filtered.tsv"
     awk '
      {
          if (!best[$2] || $12 > best[$2]) {
              best[$2] = $12
              line[$2] = $0
          }
      }
      END {
          for (c in line)
              print line[c]
      }' "$tsv" > "$tsv.unique"
    
done
# takes 2 minutes

#SANITY CHECK: print tsv of all filtered orthologs
Sanity_output="14_blast_orthologs/2_ortholog_search/all_${tree_name}.tsv"
for subdir in 14_blast_orthologs/2_ortholog_search/*Acineto*; do
  if [ -s ${subdir}/${tree_name}/blast_results.filtered.tsv.unique ]; then
  echo "$(basename "${subdir}")" >> $Sanity_output
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv.unique >> $Sanity_output
  fi
done
  # took 1 min
  
```  


#### 14.3 for A039 MB2 A044 D04

```{bash}
  
tree_name="PL_cropped_RAST_Jan21_newgenome"
OUT_FASTA="14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta"

for sample in New_NY_Acineto_genomes/*; do   
BLAST_TSV="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}/blast_results.filtered.tsv.unique"
CONTIGS_FASTA="${sample}"

# Read each line of BLAST TSV
while IFS=$'\t' read -r qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
do
    #save the sample name in a variable:
    sample_name=$(basename "$sample")
    # Determine start and end in increasing order
    if [ "$sstart" -le "$send" ]; then
        START="$sstart"
        END="$send"
        STRAND="+"
    else
        START="$send"
        END="$sstart"
        STRAND="-"
    fi

    # Extract sequence using awk
    SEQ=$(awk -v seqid="$sseqid" -v start="$START" -v end="$END" '
        BEGIN {capture=0; seq=""}
        /^>/ {capture=($0 ~ ">"seqid); next}
        capture {seq=seq $0}
        END {print substr(seq, start, end-start+1)}
    ' "$CONTIGS_FASTA")

    # Reverse complement if needed
    if [ "$STRAND" = "-" ]; then
        SEQ=$(echo "$SEQ" | rev | tr 'ACGTacgt' 'TGCAtgca')
    fi

    # Print to output FASTA with sample name
    echo ">${sample_name}_${sseqid}:${START}-${END}(${STRAND})" >> "$OUT_FASTA"
    # Wrap sequence at 80 chars per line
    echo "$SEQ" | fold -w 80 >> "$OUT_FASTA"

done < "$BLAST_TSV"
done

```



#### 14.4 aligning with MAFFT (both metagenome and new genomes)

Now, I will align the references, outgroups, metagenomic, AND new genomes together
into one big tree, so the cat step will include new-genomes too (line 546)

```{bash MAFFT, eval = FALSE}

#BEFORE USING MAFFT:
#I combined orthologs reference and outgroup fastas from `14_blast_orthologs/1_references_and_outgroups` together with our samples from `14_blast_orthologs/3_3_orthologs_from_all_samples` with cat:

tree_name="PL_cropped_RAST_Jan21"
cat 14_blast_orthologs/1_references_and_outgroups/RAST_pectin_lyase/all_PL_ref_PLUS_outgroups.fasta \
14_blast_orthologs/3_orthologs_from_all_samples/PL_cropped_RAST_Jan21_metagenome.fasta \
14_blast_orthologs/3_orthologs_from_all_samples/PL_cropped_RAST_Jan14_newgenome.fasta \
>> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta


export PATH=/programs/mafft/bin:$PATH
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

/programs/mafft/bin/mafft --auto --nuc --thread 30 \
14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta > \
14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln
  # took under 1 min
  
# --auto: chooses best strat for this data, which is FFT-NS-i (standard)
# -nuc: assume input is nucleotides
# --thread: to go faster 


```
PECTIN LYASE and POLYGALACTURONASE STRATEGY:
FFT-NS-i (Standard)
 Iterative refinement method (max. 2 iterations)


#### 14.5 IQ tree
```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-tree

tree_name="PL_cropped_RAST_Jan21"
#name this tree
mkdir 14_blast_orthologs/5_IQ_tree/${tree_name}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s 14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln -m MFP \
--prefix 14_blast_orthologs/5_IQ_tree/${tree_name}/${tree_name} -B 1000


# -s: input
# -m MFP: modelfinder plus, fo finding right phylo model (Vivi used SYM+R10)
# --prefix: change output destination/name
# -B: bootstrap
# -nt: thread number
#--redo (OPTIONAL): overwrite current tree

#took 1 min 
```














### POLYGALACTURONASE crop and filtered pipeline 1/14

####14.2 for metagenome

```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="GH28_cropped_RAST_Jan21_metagenome"
for sample in 04_metaspades/*; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_polygalacturonase/all_GH28_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample}/contigs.fasta -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 60 && $4 >= 250 && $11 <= 1e-50' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
     echo "[INFO] Step 4: deduplicating hits (keep highest bit score)..."
     tsv="$OUTDIR/blast_results.filtered.tsv"
     awk '
      {
          if (!best[$2] || $12 > best[$2]) {
              best[$2] = $12
              line[$2] = $0
          }
      }
      END {
          for (c in line)
              print line[c]
      }' "$tsv" > "$tsv.unique"
    
done
# takes 2 minutes

#SANITY CHECK: print tsv of all filtered orthologs
Sanity_output="14_blast_orthologs/2_ortholog_search/all_${tree_name}.tsv"
for subdir in 14_blast_orthologs/2_ortholog_search/*FN*; do
  if [ -s ${subdir}/${tree_name}/blast_results.filtered.tsv.unique ]; then
  echo "$(basename "${subdir}")" >> $Sanity_output
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv.unique >> $Sanity_output
  fi
done
  # took 1 min
  
```  

####14.3 for metagenome
```{bash}
  
tree_name="GH28_cropped_RAST_Jan21_metagenome"
OUT_FASTA="14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta"

for sample in 04_metaspades/*; do   
BLAST_TSV="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}/blast_results.filtered.tsv.unique"
CONTIGS_FASTA="${sample}/contigs.fasta"

# Read each line of BLAST TSV
while IFS=$'\t' read -r qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
do
    #save the sample name in a variable:
    sample_name=$(basename "$sample")
    # Determine start and end in increasing order
    if [ "$sstart" -le "$send" ]; then
        START="$sstart"
        END="$send"
        STRAND="+"
    else
        START="$send"
        END="$sstart"
        STRAND="-"
    fi

    # Extract sequence using awk
    SEQ=$(awk -v seqid="$sseqid" -v start="$START" -v end="$END" '
        BEGIN {capture=0; seq=""}
        /^>/ {capture=($0 ~ ">"seqid); next}
        capture {seq=seq $0}
        END {print substr(seq, start, end-start+1)}
    ' "$CONTIGS_FASTA")

    # Reverse complement if needed
    if [ "$STRAND" = "-" ]; then
        SEQ=$(echo "$SEQ" | rev | tr 'ACGTacgt' 'TGCAtgca')
    fi

    # Print to output FASTA with sample name
    echo ">${sample_name}_${sseqid}:${START}-${END}(${STRAND})" >> "$OUT_FASTA"
    # Wrap sequence at 80 chars per line
    echo "$SEQ" | fold -w 80 >> "$OUT_FASTA"

done < "$BLAST_TSV"
done

```

#### 14.2 for A039 MB2 A044 D04

```{bash}
    
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees
    
tree_name="GH28_cropped_RAST_Jan21_newagenome"
for sample in New_NY_Acineto_genomes/**; do   
    # Input
    query_nucleotides="14_blast_orthologs/1_references_and_outgroups/RAST_polygalacturonase/all_GH28_ref_fastas.fasta"
  
    # Output directories
    OUTDIR="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}"
    
    echo "[INFO] Step 1: Building BLAST database..."
    makeblastdb -in ${sample} -dbtype nucl -out $OUTDIR/metagenome_db
    
    echo "[INFO] Step 2: Running BLASTP..."
    blastn -query $query_nucleotides -db $OUTDIR/metagenome_db \
           -out $OUTDIR/tblastn_results.tsv \
           -evalue 1e-5 -num_threads 30 \
           -task blastn \
           -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
    
    echo "[INFO] Step 3: Filtering BLAST hits..."
    awk '$3 >= 60 && $4 >= 250 && $11 <= 1e-50' $OUTDIR/tblastn_results.tsv > $OUTDIR/blast_results.filtered.tsv
      # this step filters tblastn_results above a high-quality threshold of 
    echo "[INFO] Done."
    
     echo "[INFO] Step 4: deduplicating hits (keep highest bit score)..."
     tsv="$OUTDIR/blast_results.filtered.tsv"
     awk '
      {
          if (!best[$2] || $12 > best[$2]) {
              best[$2] = $12
              line[$2] = $0
          }
      }
      END {
          for (c in line)
              print line[c]
      }' "$tsv" > "$tsv.unique"
    
done
# takes 2 minutes

#SANITY CHECK: print tsv of all filtered orthologs
Sanity_output="14_blast_orthologs/2_ortholog_search/all_${tree_name}.tsv"
for subdir in 14_blast_orthologs/2_ortholog_search/*Acineto*; do
  if [ -s ${subdir}/${tree_name}/blast_results.filtered.tsv.unique ]; then
  echo "$(basename "${subdir}")" >> $Sanity_output
  cat ${subdir}/${tree_name}/blast_results.filtered.tsv.unique >> $Sanity_output
  fi
done
  # took 1 min
  
```  


#### 14.3 for A039 MB2 A044 D04

```{bash}
  
tree_name="GH28_cropped_RAST_Jan21_newagenome"
OUT_FASTA="14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}.fasta"

for sample in New_NY_Acineto_genomes/*; do   
BLAST_TSV="14_blast_orthologs/2_ortholog_search/$(basename "$sample")/${tree_name}/blast_results.filtered.tsv.unique"
CONTIGS_FASTA="${sample}"

# Read each line of BLAST TSV
while IFS=$'\t' read -r qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
do
    #save the sample name in a variable:
    sample_name=$(basename "$sample")
    # Determine start and end in increasing order
    if [ "$sstart" -le "$send" ]; then
        START="$sstart"
        END="$send"
        STRAND="+"
    else
        START="$send"
        END="$sstart"
        STRAND="-"
    fi

    # Extract sequence using awk
    SEQ=$(awk -v seqid="$sseqid" -v start="$START" -v end="$END" '
        BEGIN {capture=0; seq=""}
        /^>/ {capture=($0 ~ ">"seqid); next}
        capture {seq=seq $0}
        END {print substr(seq, start, end-start+1)}
    ' "$CONTIGS_FASTA")

    # Reverse complement if needed
    if [ "$STRAND" = "-" ]; then
        SEQ=$(echo "$SEQ" | rev | tr 'ACGTacgt' 'TGCAtgca')
    fi

    # Print to output FASTA with sample name
    echo ">${sample_name}_${sseqid}:${START}-${END}(${STRAND})" >> "$OUT_FASTA"
    # Wrap sequence at 80 chars per line
    echo "$SEQ" | fold -w 80 >> "$OUT_FASTA"

done < "$BLAST_TSV"
done

```



#### 14.4 aligning with MAFFT (both metagenome and new genomes)

Now, I will align the references, outgroups, metagenomic, AND new genomes together
into one big tree, so the cat step will include new-genomes too (line 546)

```{bash MAFFT, eval = FALSE}

#BEFORE USING MAFFT:
#I combined orthologs reference and outgroup fastas from `14_blast_orthologs/1_references_and_outgroups` together with our samples from `14_blast_orthologs/3_3_orthologs_from_all_samples` with cat:

tree_name="GH28_cropped_RAST_Jan21"
cat 14_blast_orthologs/1_references_and_outgroups/RAST_polygalacturonase/all_GH28_ref_PLUS_outgroups.fasta \
14_blast_orthologs/3_orthologs_from_all_samples/GH28_cropped_RAST_Jan21_metagenome.fasta \
14_blast_orthologs/3_orthologs_from_all_samples/GH28_cropped_RAST_Jan14_newagenome.fasta \
>> 14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta


export PATH=/programs/mafft/bin:$PATH
cd /local/workdir/Daphne/Floral_metagenomics/data_4-trees

/programs/mafft/bin/mafft --auto --nuc --thread 30 \
14_blast_orthologs/3_orthologs_from_all_samples/${tree_name}_PLUS_references_and_outgroups.fasta > \
14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln
  # took under 1 min
  
# --auto: chooses best strat for this data, which is FFT-NS-i (standard)
# -nuc: assume input is nucleotides
# --thread: to go faster 


```
PECTIN LYASE and POLYGALACTURONASE STRATEGY:
FFT-NS-i (Standard)
 Iterative refinement method (max. 2 iterations)


#### 14.5 IQ tree
```{bash}
cd /local/workdir/Daphne/Floral_metagenomics/data_4-tree

tree_name="GH28_cropped_RAST_Jan21"
#name this tree
mkdir 14_blast_orthologs/5_IQ_tree/${tree_name}
/programs/iqtree-2.2.2.6-Linux/bin/iqtree2 -s 14_blast_orthologs/4_aligned_orthologs_MAFFT/${tree_name}.aln -m MFP \
--prefix 14_blast_orthologs/5_IQ_tree/${tree_name}/${tree_name} -B 1000


# -s: input
# -m MFP: modelfinder plus, fo finding right phylo model (Vivi used SYM+R10)
# --prefix: change output destination/name
# -B: bootstrap
# -nt: thread number
#--redo (OPTIONAL): overwrite current tree

#took 1 min 
```




